import slider_img_1 from "../assets/images/slider-img-1.jpg";
import slider_img_2 from "../assets/images/slider-img-2.jpg";
import slider_img_3 from "../assets/images/slider-img-3.jpg";
import slider_img_5 from "../assets/images/slider-img-5.jpg";
import slider_img_4 from "../assets/images/banner.jpg";
// import clothesimage from "../assets/images/clothes.webp";
// import electronicsimage from "../assets/images/electronics.webp";
// import furnituresimage from "../assets/images/furnitures.webp";
// import miscelleousimage from "../assets/images/miscelleous.webp";
import error from "../assets/images/error.jpg";
import errors from "../assets/images/404error.jpg";
import NoItemFound from "../assets/images/NoItemFound.jpg";
import Ghost from "../assets/images/Ghost.gif";
import flipkart from "../assets/images/flipkart.svg";
const sliderImages =  [slider_img_1, slider_img_2, slider_img_3 ,slider_img_4,slider_img_5];
// const CategoryBar = [clothesimage, electronicsimage, furnituresimage ,miscelleousimage];
export {sliderImages, error, errors,NoItemFound,Ghost,flipkart};